### ISSUE TITLE
Upstream MSYS2 patches

### ISSUE THREAD

**Issue by podsvirov** [eclipse/mosquitto#2371]
I have created several patches that allow you to build `mosquitto` using `gcc` and `clang` on `Windows`.
These patches are part of the pull request to add [mosquitto](https://github.com/msys2/MINGW-packages/pull/10015) package to the [MSYS2](https://www.msys2.org/) distribution:

- [x] `001-mosquitto-2.0.13-win-threads.patch` #2375
- [x] `002-mosquitto-2.0.13-install-libmosquitto-archive.patch` #2372
- [x] `003-mosquitto-2.0.13-fix-security-module-destination.patch` #2376
- [x] `004-mosquitto-2.0.13-make-man.patch` #2374
- [x] `005-mosquitto-2.0.13-install-libmosquittopp-archive.patch` #2373

To see the compilation logs or try the prepared artifacts (prebuilt packages) go [here](https://github.com/msys2/MINGW-packages/pull/10015/checks).

I plan to create pull requests for each patch and track overall progress here.

I would be glad to receive feedback.

**Comment by podsvirov** [comment]
I created these patches based on the `v2.0.13` tag. Which `branch` can they be accepted into?

**Comment by ralight** [comment]
Thank you very much for these patches. I haven't yet merged the final two. I'm still thinking about the implications of the man pages change. For the pthreads change - does msys2 allow full use of Windows APIs? I presume that the change you are proposing means the msys2 windows pthread library will be used. In the `develop` branch I have my own Windows specific code to map Windows threads to pthreads. Will that break on msys2 in the future?

**Comment by Biswa96** [comment]
> does msys2 allow full use of Windows APIs?

Absolutely, Windows native threading APIs are prioritized over pthread. pthread APIs in mingw[^1] are wrappers over Win APIs.

[^1]: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-libraries/winpthreads/
